# Lazygit ã®ç”»é¢è¨­å®š
gui:
  tabWidth: 2

  # æ¬¡ã®ã„ãšã‚Œã‹: 'auto'ï¼ˆæ—¢å®šï¼‰ | 'en' | 'zh-CN' | 'zh-TW' | 'pl' | 'nl' | 'ja' | 'ko'
  # | 'ru' | 'pt'
  language: ja

  # ä½¿ç”¨ã™ã‚‹ Nerd Fonts ãƒãƒ¼ã‚¸ãƒ§ãƒ³
  # æ¬¡ã®ã„ãšã‚Œã‹: '2' | '3' | ç©ºæ–‡å­—åˆ—ï¼ˆæ—¢å®šï¼‰
  # ç©ºã®å ´åˆã€ã‚¢ã‚¤ã‚³ãƒ³ã‚’è¡¨ç¤ºã—ãªã„ã€‚
  nerdFontsVersion: "3"

# git ã«é–¢ã™ã‚‹è¨­å®š
git:
  # ãƒšãƒ¼ã‚¸ãƒ£ãƒ¼è¨­å®šã®é…åˆ—ã€‚å„è¦ç´ ã¯æ¬¡ã®å½¢å¼:
  #
  #   # git diff ã‚³ãƒãƒ³ãƒ‰ã® --color å¼•æ•°ã®å€¤ã€‚ä¸€éƒ¨ã®ãƒšãƒ¼ã‚¸ãƒ£ãƒ¼ã¯
  #   # 'always' ã‚’å¿…è¦ã¨ã—ã€åˆ¥ã®ãƒšãƒ¼ã‚¸ãƒ£ãƒ¼ã¯ 'never' ã‚’å¿…è¦ã¨ã™ã‚‹
  #   colorArg: "always"
  #
  #   # ä¾‹:
  #   # diff-so-fancy
  #   # delta --dark --paging=never
  #   # ydiff -p cat -s --wrap --width={{columnWidth}}
  #   pager: ""
  #
  #   # ä¾‹: 'difft --color=always'
  #   externalDiffCommand: ""
  #
  #   # true ã®å ´åˆã€ãƒšãƒ¼ã‚¸ãƒ³ã‚°ã« git ã® `diff.external` è¨­å®šã‚’ä½¿ç”¨ã™ã‚‹ã€‚
  #   # `externalDiffCommand` ã¨æ¯”ã¹ãŸåˆ©ç‚¹ã¯ã€
  #   # .gitattributes ã§ãƒ•ã‚¡ã‚¤ãƒ«ç¨®åˆ¥ã”ã¨ã«è¨­å®šã§ãã‚‹ç‚¹ã€‚å‚ç…§:
  #   # https://git-scm.com/docs/gitattributes#_defining_an_external_diff_driver.
  #   useExternalDiffGitConfig: false
  #
  # å‚ç…§: https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
  # è©³ç´°ã¯ä¸Šè¨˜ã‚’å‚ç…§ã€‚
  pagers:
    - pager: delta --dark --paging=never --side-by-side --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

  # true ã®å ´åˆã€ã‚³ãƒŸãƒƒãƒˆãƒ¡ãƒƒã‚»ãƒ¼ã‚¸å†…ã®çµµæ–‡å­—æ–‡å­—åˆ—ã‚’è§£é‡ˆï¼ˆä¾‹: :rocket: -> ğŸš€ï¼‰
  # ï¼ˆæœ¬æ¥ã¯ 'git' ã§ã¯ãªã 'gui' é…ä¸‹ã«ã‚ã‚‹ã¹ãè¨­å®šï¼‰
  parseEmoji: true
