#:schema https://developers.openai.com/codex/config-schema.json
model_reasoning_effort = "medium"
personality = "pragmatic"
forced_login_method = "chatgpt"
model = "gpt-5.3-codex"
web_search = "live"
notify = ["/Users/nasuno.ayumu/.codex/hooks/notify-terminal-notifier.sh"]

[features]
shell_snapshot = true
collab = true
apps = true

[feedback]
enabled = false

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/dotfiles"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/mario-chrome-extensions"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/smartcamp/shogun"]
trust_level = "trusted"

[tui]
status_line = ["model-with-reasoning", "project-root", "git-branch", "context-used", "five-hour-limit", "weekly-limit", "codex-version", "used-tokens"]
