#:schema https://developers.openai.com/codex/config-schema.json
model_reasoning_effort = "xhigh"
personality = "pragmatic"
forced_login_method = "chatgpt"
model = "gpt-5.3-codex"
web_search = "live"
notify = ["/Users/nasuno.ayumu/.codex/hooks/notify-terminal-notifier.sh"]
suppress_unstable_features_warning = true

[features]
shell_snapshot = true
apps = true
multi_agent = true
prevent_idle_sleep = true
voice_transcription = true

[feedback]
enabled = false

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/dotfiles"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/mario-chrome-extensions"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/smartcamp/shogun"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/smartcamp-fy26"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/cf-page-to-md"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/shogun-nix-flake"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/copy-url-as-markdown"]
trust_level = "trusted"

[tui]
status_line = ["model-with-reasoning", "project-root", "git-branch", "context-used", "five-hour-limit", "weekly-limit", "codex-version", "used-tokens"]
theme = "catppuccin-mocha"
