#:schema https://developers.openai.com/codex/config-schema.json
model_reasoning_effort = "xhigh"
personality = "pragmatic"
forced_login_method = "chatgpt"
model = "gpt-5.3-codex"
web_search = "live"
notify = ["/Users/nasuno.ayumu/.codex/hooks/notify-terminal-notifier.sh"]

[features]
shell_snapshot = true
apps = true
multi_agent = true
prevent_idle_sleep = true

[feedback]
enabled = false

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/dotfiles"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/mario-chrome-extensions"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/smartcamp/shogun"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/smartcamp-fy26"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/cf-page-to-md"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/shogun-nix-flake"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/ayuukumakuma/copy-url-as-markdown"]
trust_level = "trusted"

[tui]
status_line = ["model-with-reasoning", "project-root", "git-branch", "context-used", "five-hour-limit", "weekly-limit", "codex-version", "used-tokens"]

[apps.connector_2128aebfecb84f64a069897515042a44]
enabled = false
disabled_reason = "user"

[apps.connector_68df038e0ba48191908c8434991bbac2]
enabled = false
disabled_reason = "user"
